### ISSUE TITLE
Remove layout shift in header

### ISSUE THREAD

**Issue by iverks** [kjemidagen/kjemidagen#17]
Veldig kult arbeid du har gjort på kjemidagen! Digger touchen med en blå "new" på programsiden før første gang man klikker.

Jeg er ikke så fan av at når man hovrer over f.eks. "om kjemidagen"-lenka så shifter alt til høyre for det enda mer mot høyre:

Uten hover

![image](https://github.com/kjemidagen/kjemidagen/assets/73749615/fc0c1f51-0503-4228-ac32-a5c8defb0ed8)

Med hover 

![image](https://github.com/kjemidagen/kjemidagen/assets/73749615/2cf018f1-7e9c-4c92-8d8b-769c8e1ca830)

**Comment by trondhauklien** [comment]
Skal se på det. Ville ha en hover-effekt, og syntes det var smooth med fetere skrift, men enig i at det er kjipt at alle de andre elementene flyttes til høyre. Må vel kanskje definere en konstant vidde for å unngå det.
